{ 'Canada' => [ 'Toronto'] ,
  'China' => [ 'Beijing' ] ,
  'Spain' => [ 'Madrid' ] ,
  'France' => [ 'Paris', 'Lion' ] ,
  'Belgium' => [ 'Bruxxelles', 'Brugge', 'Kortrejk' ] ,
  'Nederlands' => [ 'Amsterdam' ] ,
  'Armenia' => [ 'Erevan' ] ,
  'Georgia' => [ 'Tbilisi', 'Kutaisi' ] ,
  'Uzbekistan' => [ 'Tashkent' ] ,
  'Japan' => [ 'Tokio' ] ,
  'Fillipines' => [ 'Manila' ] ,
  'Australia' => [ 'Kanberra' ] ,
  'New Zealand' => [ 'Wellington' ] ,
  'Israel' => [ 'Telaviv', 'Petahtikva', 'Bneibrak', 'Raanana', 'Ierushalaim', 'Haifa', 'Hadera', 'Afula', 'Netania', 'Asdod', 'Beersheva', 'Rahat', 'Modiin' ] ,
  'Emirates' => [ 'Sharm el Sheih' ] ,
  'Egypt' => [ 'Kair', 'Ramadan' ] ,
  'Czech' => [ 'Prague', 'Karlovyvary', 'Przshibram' ] ,
  'Polska' => [ 'Warszawa' ] ,
  'Romania' => [ 'Bucuresti' ] ,
  'Greece' => [ 'Afina' ] ,
  'Bulgaria' => [ 'Sofia', 'Plovdiv', 'Varna', 'Ruse', 'Alexandria', 'Karakal', 'Pirot' ] ,
  'Latvia' => [ 'Riga' ] ,
  'Lithuania' => [ 'Klaipeda' ] ,
  'Estonia' => [ 'Tallin', 'Pjarnu' ] ,
  'Mongolia' => [ 'Ulanbaatar' ] ,
  'Russia' => [ 'Moscow', 'St. Petersburg', 'Novgorod', 'Kaliningrad', 'Murmansk', 'Arkhangelsk', 'Vologda', 'Jaroslavl', 'Kostroma', 'Nijnii Novgorod', 'Vladimir', 'Smolensk', 'Tula', 'Kaluga', 'Brjansk', 'Orjol', 'Kursk', 'Lipetck', 'Tambov', 'Penza', 'Cheboksary', 'Kirov', 'Penza', 'Saratov', 'Voronezh', 'Belgorod', 'Volgograd', 'Rostov-na-Donu', 'Krasnodar', 'Stavropol', 'Astrahan', 'Sochi', 'Izhevsk', 'Ekaterinburg', 'Perm', 'Cheljabinsk', 'Magnitogorsk', 'Tjumen', 'Norilsk', 'Surgut', 'Omsk', 'Novosibirsk', 'Barnaul', 'Krasnojarsk', 'Irkutsk', 'Bratsk', 'Chita', 'Komsomolsk-na-Amure', 'Vladivostok', 'Nahodka', 'Juzhnosahalinsk' ] ,
  'Ukraine' => [ 'Kiev', 'Odessa', 'Donetck', 'Dnepropetrovsk', 'Kherson', 'Kharkov', 'Ovidiopol', 'Balta', 'Uman', 'Ternopol', 'Lvov', 'Vinnica', 'Slavuta', 'Chernigov', 'Cherkassy', 'Poltava', 'Kremenchug', 'Kirovograd', 'Krivoyrog', 'Zaporozhje', 'Nikolaev', 'Melitopol', 'Mariupol', 'Rovno' ] ,
  'Kazakhstan' => [ 'Astana', 'Alma-Aty' ] ,
  'Belarus' => [ 'Minsk', 'Brest', 'Mogilev', 'Pinsk', ] ,
  'USA' => [ 'New York', 'St.Louis' ] ,
  'Brazil' => [ 'Rio de Janeiro', 'San Paulu', 'Balsas' ] ,
  'Ecuador' => [ 'Guayaquil' ] ,
  'Peru' => [ 'Lima', 'Trujillo' ] ,
  'Chili' => [ 'Valparaiso', 'Santiago' ] ,
  'Argentina' => [ 'Mendosa', 'Santa Rosa', 'Rio Gallegos'] ,
  'Columbia' => [ 'Bogota', 'Manisales'] ,
  'Venesuella' => [ 'Caracas' ] ,
  'Bolivia' => [ 'Cochabamba', 'Montero', 'Santa Cruz'] ,
  'Mexica' => [ 'Mexico' ] ,
  'Germany' => [ 'Berlin' ] ,
  'Spain' => [ 'Madrid' ] ,
  'Turkey' => [ 'Istambul', 'Bursa', 'Izmir', 'Samsun' ] }.each do |cn,clist|
  country = Country.create!(name: cn)
    clist.each do |cityn|
      country.cities << City.create(name: cityn)
    end
end
